language: python
python:
   - "3.5"
install:
   - pip install pytest pytest-cov
   - pip install coveralls
script:
   - py.test -v --cov-config .coveragerc --cov=c4cs-f18-rpn 
after_sucess:
   - coveralls
